blog-app/article/urls.py
from django.urls import path


from . import views

app_name = "article"


urlpatterns = [
    path('', views.articles, name="articles"),
    path('detail/<int:article_id>', views.detail, name="detail"),
    path('add_article/', views.create_article, name="createArticle"),
    path('edit/<int:article_id>', views.edit, name="edit"),
    path('delete/<int:article_id>', views.delete, name="delete"),
    path('comment/<int:article_id>', views.addComment, name="comment")
]

blog-app/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article.views import index, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('articles/', include('article.urls'))
]

blog-app/user/urls.py
from django.urls import path

from .views import registerUser, loginUser, logoutUser, dashboard, userIndex

app_name = "user"

urlpatterns = [
    path('', userIndex),
    path('register/', registerUser, name="register"),
    path('login/', loginUser, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('dashboard/', dashboard, name="dashboard")
]

blog-app/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">BATTOS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'user:dashboard' %}">Dashboard</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">Log out</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'user:login'%}">Login</a>
            <a class="dropdown-item" href="{% url 'user:register'%}">Register</a>
            {% endif %}
            
          </div>
        </li>
      </ul>
    </div>
</nav>