blog-app/article/urls.py
from django.urls import path


from . import views

app_name = "article"


urlpatterns = [
    path('', views.articles, name="articles"),
    path('detail/<int:article_id>', views.detail, name="detail"),
    path('add_article/', views.create_article, name="createArticle"),
    path('edit/<int:article_id>', views.edit, name="edit"),
    path('delete/<int:article_id>', views.delete, name="delete"),
    path('comment/<int:article_id>', views.addComment, name="comment")
]

blog-app/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article.views import index, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('articles/', include('article.urls'))
]

blog-app/article/models.py
from django.db import models

from ckeditor.fields import RichTextField


class Article(models.Model):

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name="Author")
    title = models.CharField(max_length=120, verbose_name="Title")
    content = RichTextField(verbose_name="Content")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Publish date")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Article", related_name="comments")
    comment_author = models.CharField(max_length=30, verbose_name="Name")
    comment_author_email = models.EmailField(max_length=50, verbose_name="Email Address")
    comment_content = models.CharField(max_length=200, verbose_name="Comment")
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-pub_date']

blog-app/article/forms.py
from django import forms

from .models import Article, Comment
from ckeditor.widgets import CKEditorWidget

class ArticleForm(forms.ModelForm):

    content = forms.CharField(widget=CKEditorWidget)

    class Meta:

        model = Article
        fields = ["title", "content"]

blog-app/article/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import ArticleForm
from .models import Article, Comment

def index(request):

    last_article = Article.objects.first()

    if last_article:

        return render(request, "index.html", {"article":last_article})

    return render(request, "index.html")


def about(request):

    return render(request, "about.html")


def articles(request):

    keyword = request.GET.get("keyword")

    if keyword:

        articles = Article.objects.filter(title__contains=keyword)

        return render(request, "articles.html", {"articles":articles})

    articles = Article.objects.all()

    return render(request, "articles.html", {"articles":articles})

@login_required(login_url="user:login")
def create_article(request):

    form = ArticleForm(request.POST or None)

    if form.is_valid():

        newArticle = form.save(commit=False)
        newArticle.author = request.user
        newArticle.save()

        messages.success(request, "Article added successfully.")
        return redirect("index")

    context = {
        "form": form
    }

    return render(request, "add_article.html", context)


@login_required(login_url="user:login")
def delete(request, article_id):

    article = get_object_or_404(Article, id=article_id)

    article.delete()

    messages.success(request, "Article deleted successfully.")
    return redirect("user:dashboard")



@login_required(login_url="user:login")
def edit(request, article_id):

    article = get_object_or_404(Article, id=article_id)

    form = ArticleForm(request.POST or None, instance=article)

    if form.is_valid():

        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Article updated successfully.")
        return redirect("index")

    return render(request, "update.html", {'form':form})



def detail(request, article_id):

    article = get_object_or_404(Article, id=article_id)

    comments = article.comments.all()

    context = {
        "article": article,
        "comments": comments
    }

    return render(request, 'article.html', context)



def addComment(request, article_id):

    article = get_object_or_404(Article, id=article_id)

    if request.method == "POST":

        comment_author = request.POST.get("comment_author")
        comment_author_email = request.POST.get("comment_author_email")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author, comment_author_email=comment_author_email, comment_content=comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail", kwargs={"article_id":article_id}))

blog-app/templates/about.html
{% extends 'layout.html' %}

{% block title %}
About
{% endblock title %}

{% block body %}

<div class="jumbotron text-center">
    <h3>About</h3>
    <hr>
    <p> ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nunc odio, scelerisque sed mauris ut, viverra ullamcorper velit. Nunc nec mauris ac tellus elementum vestibulum. Aliquam neque justo, iaculis vitae neque quis, auctor vestibulum tortor. Suspendisse lorem nibh, scelerisque non malesuada vel, accumsan vitae enim. Mauris tincidunt commodo pellentesque. Fusce aliquam nunc vel ligula ullamcorper fermentum. Donec hendrerit orci at pretium facilisis. Nunc at malesuada lorem. Nunc ornare massa ut magna mollis, at fringilla lectus condimentum. Mauris vitae facilisis dui, quis aliquam enim. Suspendisse auctor at leo ut commodo.

        Ut suscipit elit id suscipit fringilla. In eget libero sed e</p>
</div>

{% endblock body %}

blog-app/templates/add_article.html
{% extends 'layout.html' %}

{% block title %}
Add Article
{% endblock title %}

{% block body %}
{% load crispy_forms_tags %}

{% load static %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<div style="padding-left: 10%; padding-right: 10%;">
  <h3>Create Article</h3>
  <hr>
  <form class="form-signin" method="POST">
      {% csrf_token %}
    
      {% if form %}
        {{ form.media }}
        {{ form|crispy }}
        <br>
        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Add Article</button>
      {% else %}
      <div class="alert alert-danger" role="alert">
        Adding articles is not allowed.
      </div>
      {% endif %}
    
  </form>
</div>

{% endblock body %}

blog-app/templates/article.html
{% extends 'layout.html' %}

{% block title %}

    {% if article %}
    {{ article.title }}
    {% else %}
    Article
    {% endif %}

{% endblock title %}


{% block body %}

<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>


<div>

    <div>

        <h1>{{ article.title }}</h1>

        <hr>


        <small>
            Author : {{ article.author }}
        </small>

        <br>

        <small>Publish date : {{ article.pub_date }}</small>


        <hr>

        <p>
            {{ article.content|safe }}
        </p>

        <br>
        <hr>
        <br>

        <h5>Comment</h5>
        <br>
        <form method="POST" action="{% url 'article:comment' article.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="comment_author">Name</label>
                <input type="text" name="comment_author" class="form-control" rows="3" placeholder="">
            </div>
            <div class="form-group">
                <label for="comment_author_email">Email Address</label>
                <input type="email" name="comment_author_email" class="form-control" rows="3" placeholder="">
                <small>* Nobody will see your email address except us.</small>
            </div>
            <div class="form-group">
              <label for="comment_content">Comment</label>
              <textarea name="comment_content" class="form-control" rows="3" placeholder=""></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Publish</button>
        </form>
        <br><hr><br>
        <h5>Comments</h5>
        <br>
        {% if comments %}
        <table class="table table-striped">
            <tbody>
                {% for comment in comments %}
                    <tr>
                        <td style="width: 10%;">{{ comment.comment_author }}</td>
                        <td style="width: 15%;">{{ comment.pub_date }}</td>
                        <td>{{ comment.comment_content }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <br><br>
        <div class="alert alert-danger" role="alert">
            No comment.
        </div>
        {% endif %}
       
        

    </div>

    
</div>



{% endblock body %}

blog-app/templates/articles.html
{% extends 'layout.html' %}

{% block title %}
Articles
{% endblock title %}

{% block body %}

<div style="padding-left: 10%; padding-right: 10%;">

    <h3>Articles</h3>
    <hr>
    <form class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Keywords" aria-label="Search" name="keyword">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <br>

</div>
{% if articles %}

{% for article in articles %}
    
<div style="padding-left: 10%; padding-right: 10%;">
    <div class="jumbotron">
        <div class="row">

            <div class="col-lg-8">

                <h1>{{ article.title }}</h1>

                <hr>


                <small>
                    Author : {{ article.author }}
                </small>

                <br>

                <small>Publish date : {{ article.pub_date }}</small>


                <hr>

                <p>
                    {{ article.content|safe|truncatewords:100 }}
                </p>

                <a href="{% url 'article:detail' article.id %}">Read more</a>

            </div>
        </div>

    </div>
    <br><br>
    <hr>

    <br><br>

</div>

{% endfor %}

{% else %}
<div class="alert alert-danger" role="alert">
    No articles were found or no articles related to the specified keywords were found.
</div>
{% endif %}

{% endblock body %}

blog-app/templates/dashboard.html
{% extends 'layout.html' %}

{% block title %}
Dashboard
{% endblock title %}

{% block body %}

<div>
    <h3>Dashboard</h3>
    <small>Wellcome, {{user.username}}</small>
    <hr>
    <h4>User Info</h4>
    {% if user.is_authenticated %}
    <p>First Name : {{user.first_name}}</p>
    <p>Last Name : {{user.last_name}}</p>
    <p>Email Adress : {{user.email}}</p>
    <p>Username : {{user.username}}</p>
    <br>
    {% else %}
    <div class="alert alert-danger" role="alert">
        No info.
    </div>
    {% endif %}
    <hr>
    <h4>Articles</h4>
    <br>
    
    <br>
    {% if articles %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Publish date</th>
            <th scope="col"></th>
            <th scope="col"><a href="{% url 'article:createArticle' %}"><button type="button" class="btn btn-primary">Add Article</button></a></th>
          </tr>
        </thead>
        <tbody>
            {% for article in articles %}

            <tr>
                <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                <td>{{article.pub_date}}</td>
                <th><a href="{% url 'article:edit' article.id %}"><button type="button" class="btn btn-primary">Edit</button></a></th>
                <th><a href="{% url 'article:delete' article.id %}"><button type="button" class="btn btn-danger">Delete</button></a></th>
            </tr>
                
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <br>
    <a href="{% url 'article:createArticle' %}"><button type="button" class="btn btn-primary">Add Article</button></a>
    <br><br>
    <div class="alert alert-danger" role="alert">
        You have no articles.
    </div>
    {% endif %}

    <br><br><hr>
    <h4>Comments</h4>
    <br>

    {% if comments %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">E-Mail</th>
            <th scope="col">Date</th>
            <th scope="col">Comment</th>
            <th scope="col">Article</th>
          </tr>
        </thead>
        <tbody>
            {% for comment in comments %}

            <tr>
                <td style="width: 10%;">{{ comment.comment_author }}</td>
                <td style="width: 10%;">{{ comment.comment_author_email }}</td>
                <td style="width: 10%;">{{ comment.pub_date }}</td>
                <td>{{ comment.comment_content }}</td>
                <td style="width: 15%;">{{ comment.article.title }}</td>
            </tr>
                
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <br><br>
    <div class="alert alert-danger" role="alert">
        There are no comments on your articles.
    </div>
    {% endif %}
</div>

{% endblock body %}

blog-app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
Home
{% endblock title %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col">
        <div class="jumbotron text-center">
            <h3>Lorem Ipsum</h3>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu libero quam. Donec sed mi vel justo sodales vulputate eu pretium mauris. In imperdiet molestie nibh, sit amet congue sem hendrerit sed. Curabitur quam lorem, sollicitudin id erat eget, pretium egestas mauris. Fusce sem diam, auctor ut euismod vitae, maximus nec justo. Praesent eleifend luctus orci et pulvinar. Etiam lobortis, massa vitae hendrerit euismod, velit velit ultricies lorem, vitae commodo augue libero sit amet magna. Donec iaculis, est eget efficitur molestie, lectus velit lacinia nunc, vel sollicitudin massa enim ac nulla. Sed et pretium justo. Nullam auctor, sapien quis pharetra tincidunt, neque dui malesuada mi, a finibus magna nisi vel ex. Nam elementum, sem ut sodales fringilla, dolor quam tempor risus, non scelerisque orci justo vel dui. Nulla fringilla aliquet turpis, a vehicula orci egestas id. Vestibulum vestibulum odio sed felis lobortis vestibulum.</p>
        </div>

        {% if article %}

            <div class="jumbotron">
                <h3>Last added article.</h3>
                <hr>
                <h2>{{ article.title }}</h2>

                <hr>


                <small>
                    Author : {{ article.author }}
                </small>

                <br>

                <small>Publish date : {{ article.pub_date }}</small>


                <hr>

                <p>
                    {{ article.content|safe|truncatewords:100 }}
                </p>

                <a href="{% url 'article:detail' article.id %}">Read more</a>
            
            </div>
        {% endif %}
    </div>
    
</div>

{% endblock body %}

blog-app/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <title>
        {% block title %}
            BATTOS
        {% endblock title %}
    </title>
</head>
<body>
    
    {% include 'includes/navbar.html' %}

    {% if messages %}
    <div id="message">
        <ul class="messages" style="padding: 1%;">
            {% for message in messages %}
            
                <div class="alert alert-{{message.tags}}" role="alert">
                    <p>{{ message }} <button id="close" class="material-icons" style="float:right;">close</button></p>
                </div>
            
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    
    <div style="padding: 3%;">
        {% block body %}
        <div class="alert alert-danger" role="alert">
            No content.
        </div>
        {% endblock body %}
    </div>

    
    <script>
        $(document).ready(function(){
            $("#close").click(function(){
              $("#message").remove();
            });
          });
    </script>

    

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

blog-app/templates/login.html
{% extends 'layout.html' %}

{% block title %}
Login
{% endblock title %}

{% block body %}
{% load crispy_forms_tags %}
<body>
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h5 class="card-title text-center">Login</h5>
              <form class="form-signin" method="POST">
                  {% csrf_token %}
                
                  {% if form %}
                    {{ form|crispy }}
                    <br>
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Login</button>
                  {% else %}
                  <div class="alert alert-danger" role="alert">
                    Login is not allowed.
                  </div>
                  {% endif %}
                
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>
{% endblock body %}

blog-app/templates/register.html
{% extends 'layout.html' %}

{% block title %}
Register
{% endblock title %}

{% block body %}
{% load crispy_forms_tags %}
<body>
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h5 class="card-title text-center">Register</h5>
              <form class="form-signin" method="POST">
                  {% csrf_token %}
                
                  {% if form %}
                    {{ form|crispy }}
                    <br>
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Register</button>
                  {% else %}
                  <div class="alert alert-danger" role="alert">
                    Registration is not allowed.
                  </div>
                  {% endif %}
                
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>
{% endblock body %}

blog-app/templates/update.html
{% extends 'layout.html' %}

{% block title %}
Update
{% endblock title %}

{% block body %}
{% load crispy_forms_tags %}

{% load static %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<div style="padding-left: 10%; padding-right: 10%;">
  <h3>Edit Article</h3>
  <hr>
  <form class="form-signin" method="POST">
      {% csrf_token %}
    
      {% if form %}
        {{ form.media }}
        {{ form|crispy }}
        <br>
        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Update Article</button>
      {% else %}
      <div class="alert alert-danger" role="alert">
        Something went wrong.
      </div>
      {% endif %}
    
  </form>
</div>

{% endblock body %}